### ISSUE TITLE
use this service for Ophan's Heatphan

### ISSUE THREAD

**Issue by twrichards** [guardian/fastly-content-fanout#10]
There is currently some browser refresh logic in Heatphan to keep fronts pages up-to-date, this would be more timely and more efficient if it used this service (and would also provide a place for us to test the service with real users but internal so lower risk).

CC @jonflynng @SHession

**Comment by waisingyiu** [comment]
It has been implemented in the following PRs:
- https://github.com/guardian/ophan/pull/6026
- https://github.com/guardian/ophan/pull/6091
- https://github.com/guardian/ophan/pull/6114
- https://github.com/guardian/ophan/pull/6149
